//! Pack ↔ Hermes config.yaml synchronisation.
//!
//! Stage 3b of the Pack subsystem rollout: when a Pack is enabled
//! we translate its `mcp_servers:` declarations into entries inside
//! `~/.hermes/config.yaml`'s `mcp_servers:` map; when it's disabled
//! we remove them. Hermes' gateway picks them up on its next start
//! (Hermes 0.10 has no `/reload-mcp` HTTP endpoint, see
//! `mcp_server/mod.rs::register_with_hermes` — gateway restart is
//! the only mechanism).
//!
//! Why prefix instead of a sidecar tag file?
//!
//! Each Pack-injected entry uses the key
//! `pack__<pack_id>__<server_id>` so we can:
//!
//! 1. Identify Pack-owned entries by string match (no extra
//!    metadata file to keep in sync with config.yaml).
//! 2. Clean them up reliably even if the Pack folder is deleted
//!    before disable (no need to re-read the manifest to know
//!    which keys to remove — we just walk config.yaml looking for
//!    the prefix).
//! 3. Coexist peacefully with user-curated mcp_servers entries —
//!    those don't carry the prefix.
//!
//! Trade-off: the existing MCP Settings page will list these
//! prefixed entries verbatim. Stage 4+ adds UI filtering so they
//! show up grouped under their Pack.

use std::collections::HashMap;
use std::path::Path;

use crate::hermes_config;
use crate::pack::manifest::{McpServerSpec, PackManifest};
use crate::pack::templates::{resolve, resolve_env, TemplateContext};

/// Prefix added to every Pack-owned key under `mcp_servers:` in
/// config.yaml. Two underscores so it can never collide with a
/// hand-written user id (Hermes accepts identifier-like keys but
/// the convention is single-underscore-separated names).
pub const PACK_KEY_PREFIX: &str = "pack__";

/// Build the Hermes config.yaml key for one Pack MCP server.
/// `pack__<pack_id>__<server_id>`. Sorted with other entries; the
/// prefix puts them in their own visual cluster.
pub fn key_for(pack_id: &str, server_id: &str) -> String {
    format!("{PACK_KEY_PREFIX}{pack_id}__{server_id}")
}

/// True if the given config.yaml key was generated by us for a
/// specific Pack. Used by `disable` to identify ownership.
#[allow(dead_code)] // wired in stage 3c (config.yaml scan path)
pub fn key_belongs_to_pack(key: &str, pack_id: &str) -> bool {
    let prefix = format!("{PACK_KEY_PREFIX}{pack_id}__");
    key.starts_with(&prefix)
}

/// Translate one Pack MCP spec into the JSON value Hermes expects
/// under `mcp_servers.<key>`.
///
/// Hermes schema (verified against the
/// hermes-agent docs):
///
/// ```yaml
/// mcp_servers:
///   <key>:
///     command: "<argv[0]>"          # stdio
///     args:    [<argv[1]>, ...]     # stdio
///     env:     { K: V, ... }        # stdio + http
/// ```
///
/// `transport` other than `"stdio"` is not yet supported; the
/// stage 3b scope is precompiled-binary stdio MCPs (per the iron
/// rule from the Pack architecture decision: ship binaries inside
/// the Pack folder).
pub fn spec_to_hermes_entry(spec: &McpServerSpec, ctx: &TemplateContext) -> serde_json::Value {
    let argv: Vec<String> = spec.command.iter().map(|s| resolve(s, ctx)).collect();
    let env = resolve_env(&spec.env, ctx);

    let command = argv.first().cloned().unwrap_or_default();
    let args: Vec<serde_json::Value> = argv
        .iter()
        .skip(1)
        .map(|a| serde_json::Value::String(a.clone()))
        .collect();

    let mut entry = serde_json::Map::new();
    entry.insert("command".to_string(), serde_json::Value::String(command));
    if !args.is_empty() {
        entry.insert("args".to_string(), serde_json::Value::Array(args));
    }
    if !env.is_empty() {
        let mut env_map = serde_json::Map::new();
        for (k, v) in env {
            env_map.insert(k, serde_json::Value::String(v));
        }
        entry.insert("env".to_string(), serde_json::Value::Object(env_map));
    }

    serde_json::Value::Object(entry)
}

/// Build the full set of `mcp_servers.<key> = entry` updates for a
/// single Pack at enable time. Used both by the live IPC path and
/// by tests.
pub fn enable_updates(
    manifest: &PackManifest,
    ctx: &TemplateContext,
) -> HashMap<String, serde_json::Value> {
    let mut updates = HashMap::with_capacity(manifest.mcp_servers.len());
    for spec in &manifest.mcp_servers {
        if !spec.auto_start {
            // `auto_start: false` means the Pack expects the user
            // to invoke this server explicitly; we still register
            // it so Hermes knows about it, but Hermes will lazy-
            // start on first reference. Schema is the same either
            // way; we surface auto_start to UI in stage 4.
        }
        let key = key_for(&manifest.id, &spec.id);
        updates.insert(key, spec_to_hermes_entry(spec, ctx));
    }
    updates
}

/// Apply enable_updates to the running config.yaml. Atomic per
/// `hermes_config::write_channel_yaml_fields`. No-op when the
/// manifest declares no MCP servers.
#[allow(dead_code)] // wired in stage 3c
pub fn apply_enable(
    manifest: &PackManifest,
    ctx: &TemplateContext,
    journal: Option<&Path>,
) -> std::io::Result<()> {
    let updates = enable_updates(manifest, ctx);
    if updates.is_empty() {
        return Ok(());
    }
    hermes_config::write_channel_yaml_fields("mcp_servers", &updates, journal)
}

/// Build the deletion-update set for a Pack at disable time.
///
/// Without read access to the live config.yaml we can't enumerate
/// existing keys, so we assume the manifest is the source of truth
/// for what we wrote. If the user uninstalled the Pack folder
/// before disabling, the caller should fall back to scanning
/// config.yaml for keys with the `pack__<id>__` prefix —
/// `disable_updates_from_keys` covers that path.
#[allow(dead_code)] // wired in stage 3c
pub fn disable_updates(manifest: &PackManifest) -> HashMap<String, serde_json::Value> {
    let mut updates = HashMap::with_capacity(manifest.mcp_servers.len());
    for spec in &manifest.mcp_servers {
        let key = key_for(&manifest.id, &spec.id);
        // JSON null = delete in `write_channel_yaml_fields`.
        updates.insert(key, serde_json::Value::Null);
    }
    updates
}

/// Same shape as [`disable_updates`] but driven by an explicit
/// list of keys (e.g. obtained by scanning config.yaml when the
/// Pack folder is gone).
#[allow(dead_code)] // wired in stage 3c
pub fn disable_updates_from_keys(keys: &[String]) -> HashMap<String, serde_json::Value> {
    keys.iter()
        .map(|k| (k.clone(), serde_json::Value::Null))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pack::manifest::{parse, McpServerSpec, PackManifest};
    use std::collections::BTreeMap;
    use std::path::PathBuf;

    fn ctx() -> TemplateContext {
        let mut config = BTreeMap::new();
        config.insert("token".to_string(), "tok-1".to_string());
        TemplateContext {
            platform: "darwin-arm64".to_string(),
            pack_data_dir: PathBuf::from("/abs/pack-data/foo"),
            pack_config: config,
        }
    }

    fn argv(items: &[&str]) -> Vec<String> {
        items.iter().map(|s| s.to_string()).collect()
    }

    #[test]
    fn key_for_uses_double_underscore_prefix() {
        assert_eq!(key_for("foo", "srv"), "pack__foo__srv");
    }

    #[test]
    fn key_belongs_to_pack_matches_only_owned() {
        assert!(key_belongs_to_pack("pack__foo__srv", "foo"));
        assert!(!key_belongs_to_pack("pack__bar__srv", "foo"));
        assert!(!key_belongs_to_pack("user_curated", "foo"));
    }

    #[test]
    fn spec_with_argv_only_yields_command_plus_args() {
        let spec = McpServerSpec {
            id: "srv".to_string(),
            transport: "stdio".to_string(),
            command: argv(&["./mcp/srv/server-${platform}", "--data", "${pack_data_dir}"]),
            env: BTreeMap::new(),
            auto_start: true,
            timeout_ms: 30_000,
        };
        let entry = spec_to_hermes_entry(&spec, &ctx());
        let obj = entry.as_object().expect("object");
        assert_eq!(
            obj["command"].as_str(),
            Some("./mcp/srv/server-darwin-arm64")
        );
        let args = obj["args"].as_array().expect("args array");
        assert_eq!(args.len(), 2);
        assert_eq!(args[0].as_str(), Some("--data"));
        assert_eq!(args[1].as_str(), Some("/abs/pack-data/foo"));
        assert!(obj.get("env").is_none(), "env omitted when empty");
    }

    #[test]
    fn spec_with_single_command_no_args_omits_args_field() {
        let spec = McpServerSpec {
            id: "srv".to_string(),
            transport: "stdio".to_string(),
            command: argv(&["./bin"]),
            env: BTreeMap::new(),
            auto_start: true,
            timeout_ms: 30_000,
        };
        let entry = spec_to_hermes_entry(&spec, &ctx());
        let obj = entry.as_object().expect("object");
        assert_eq!(obj["command"].as_str(), Some("./bin"));
        assert!(obj.get("args").is_none(), "args omitted when empty");
    }

    #[test]
    fn spec_env_is_resolved_and_serialised() {
        let mut env = BTreeMap::new();
        env.insert("DATA".to_string(), "${pack_data_dir}/x".to_string());
        env.insert("TOKEN".to_string(), "${pack_config.token}".to_string());
        env.insert("LITERAL".to_string(), "static".to_string());
        let spec = McpServerSpec {
            id: "srv".to_string(),
            transport: "stdio".to_string(),
            command: argv(&["./bin"]),
            env,
            auto_start: true,
            timeout_ms: 30_000,
        };
        let entry = spec_to_hermes_entry(&spec, &ctx());
        let env_obj = entry["env"].as_object().expect("env obj");
        assert_eq!(env_obj["DATA"].as_str(), Some("/abs/pack-data/foo/x"));
        assert_eq!(env_obj["TOKEN"].as_str(), Some("tok-1"));
        assert_eq!(env_obj["LITERAL"].as_str(), Some("static"));
    }

    #[test]
    fn enable_updates_keys_each_server_under_pack_prefix() {
        let manifest = parse_manifest(
            r##"
schema_version: 1
id: cross_border_ecom
version: "1.0.0"
mcp_servers:
  - id: amazon-sp
    command: ["./mcp/amazon-sp/server-${platform}"]
  - id: dbhub
    command: ["dbhub", "--config", "${pack_data_dir}/dbhub.json"]
"##,
        );
        let updates = enable_updates(&manifest, &ctx());
        assert_eq!(updates.len(), 2);
        assert!(updates.contains_key("pack__cross_border_ecom__amazon-sp"));
        assert!(updates.contains_key("pack__cross_border_ecom__dbhub"));
    }

    #[test]
    fn disable_updates_emits_nulls_for_each_server() {
        let manifest = parse_manifest(
            r##"
schema_version: 1
id: cross_border_ecom
version: "1.0.0"
mcp_servers:
  - id: amazon-sp
    command: ["./bin"]
  - id: dbhub
    command: ["./bin2"]
"##,
        );
        let updates = disable_updates(&manifest);
        assert_eq!(updates.len(), 2);
        for v in updates.values() {
            assert!(v.is_null(), "delete entries must be JSON null");
        }
    }

    #[test]
    fn disable_updates_from_keys_round_trips() {
        let keys = vec!["pack__foo__a".to_string(), "pack__foo__b".to_string()];
        let updates = disable_updates_from_keys(&keys);
        assert_eq!(updates.len(), 2);
        assert!(updates["pack__foo__a"].is_null());
    }

    #[test]
    fn manifest_with_no_mcp_servers_yields_no_updates() {
        let manifest = parse_manifest(
            r##"
schema_version: 1
id: tiny
version: "1.0.0"
"##,
        );
        let updates = enable_updates(&manifest, &ctx());
        assert!(updates.is_empty());
    }

    fn parse_manifest(yaml: &str) -> PackManifest {
        match parse(yaml) {
            crate::pack::manifest::ManifestLoadOutcome::Loaded(m) => *m,
            other => panic!("expected Loaded, got {other:?}"),
        }
    }
}
