//! Voice IPC — T8.1 (ASR) + T8.2 (TTS) + T8.5 (audit log).
//!
//! Multi-provider support: OpenAI, Zhipu (智谱), Groq, Edge TTS.
//! The user picks a provider in Settings → Voice; the backend routes
//! to the correct endpoint and adapts the request/response format.
//!
//! 2026-04-26 — split out of a single 850-line file into:
//! - [`provider`] — multi-provider abstraction (endpoints, models, voices)
//! - [`recorder`] — system mic capture (`cpal`) + PCM↔WAV conversion
//! - this module — the `#[tauri::command]` IPC handlers + on-disk
//!   `voice.json` config + audit log
//!
//! `recorder::voice_record` and `recorder::voice_record_stop` keep
//! their original module path because Tauri's `__cmd__` helper
//! generated by `#[tauri::command]` doesn't follow `pub use`
//! re-exports; `lib.rs` references them as
//! `ipc::voice::recorder::voice_record`.

mod provider;
// `recorder` is `pub` so `lib.rs`'s `invoke_handler!` macro can
// reference `ipc::voice::recorder::voice_record(...)`. Tauri's
// `#[tauri::command]` annotation generates a `__cmd__<name>`
// helper at the function's defining module, and that helper
// doesn't follow `pub use` re-exports — so the registration
// path has to be the original module path.
pub mod recorder;
// Same constraint for `tts::voice_tts` — the `#[tauri::command]`
// helper for `voice_tts` lives in `tts.rs`, so `lib.rs` registers
// it as `ipc::voice::tts::voice_tts`.
pub mod tts;

use std::path::PathBuf;

use base64::Engine;
use serde::{Deserialize, Serialize};
use tauri::State;

use crate::error::{IpcError, IpcResult};
use crate::fs_atomic;
use crate::state::AppState;

use provider::{parse_provider, VoiceProvider};

// ───────────────────────── Types ─────────────────────────

#[derive(Debug, Clone, Serialize)]
pub struct VoiceTranscribeResult {
    pub text: String,
    pub language: Option<String>,
    pub duration_ms: Option<u64>,
}

#[derive(Debug, Clone, Serialize)]
pub struct VoiceTtsResult {
    pub audio_path: String,
    pub audio_base64: String,
    pub duration_ms: Option<u64>,
}

#[derive(Debug, Clone, Serialize)]
pub struct VoiceConfig {
    pub asr_provider: String,
    pub tts_provider: String,
    pub asr_endpoint: Option<String>,
    pub asr_api_key_set: bool,
    pub tts_endpoint: Option<String>,
    pub tts_api_key_set: bool,
    pub tts_voice: String,
    pub tts_speed: f32,
    pub hotkey: String,
    pub available_asr_providers: Vec<String>,
    pub available_tts_providers: Vec<String>,
    pub asr_voices: Vec<String>,
    pub tts_voices: Vec<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct VoiceConfigUpdate {
    pub asr_provider: Option<String>,
    pub asr_endpoint: Option<String>,
    pub asr_api_key: Option<String>,
    pub tts_provider: Option<String>,
    pub tts_endpoint: Option<String>,
    pub tts_api_key: Option<String>,
    pub tts_voice: Option<String>,
    pub tts_speed: Option<f32>,
    pub hotkey: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VoiceAuditEntry {
    pub event_type: String,
    pub timestamp: i64,
    pub provider: String,
    pub duration_ms: u64,
    pub success: bool,
}

// ───────────────────────── Config ─────────────────────────

fn voice_config_path() -> std::io::Result<PathBuf> {
    let home = std::env::var_os("HOME")
        .or_else(|| std::env::var_os("USERPROFILE"))
        .ok_or_else(|| std::io::Error::new(std::io::ErrorKind::NotFound, "no HOME"))?;
    Ok(PathBuf::from(home).join(".hermes").join("voice.json"))
}

fn audit_dir() -> std::io::Result<PathBuf> {
    let home = std::env::var_os("HOME")
        .or_else(|| std::env::var_os("USERPROFILE"))
        .ok_or_else(|| std::io::Error::new(std::io::ErrorKind::NotFound, "no HOME"))?;
    let dir = PathBuf::from(home).join(".hermes").join("voice_audit");
    std::fs::create_dir_all(&dir)?;
    Ok(dir)
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub(super) struct VoiceConfigFile {
    #[serde(default)]
    asr_provider: Option<String>,
    #[serde(default)]
    asr_endpoint: Option<String>,
    #[serde(default)]
    asr_api_key: Option<String>,
    #[serde(default)]
    tts_provider: Option<String>,
    #[serde(default)]
    tts_endpoint: Option<String>,
    #[serde(default)]
    tts_api_key: Option<String>,
    #[serde(default = "default_voice")]
    tts_voice: String,
    #[serde(default = "default_speed")]
    tts_speed: f32,
    #[serde(default = "default_hotkey")]
    hotkey: String,
}

fn default_voice() -> String {
    "alloy".into()
}

fn default_speed() -> f32 {
    1.0
}

fn default_hotkey() -> String {
    "Meta+Space".into()
}

pub(super) fn load_config() -> VoiceConfigFile {
    let path = match voice_config_path() {
        Ok(p) => p,
        Err(_) => return VoiceConfigFile::default(),
    };
    if !path.exists() {
        return VoiceConfigFile::default();
    }
    let data = std::fs::read_to_string(&path).unwrap_or_default();
    serde_json::from_str(&data).unwrap_or_default()
}

fn save_config(cfg: &VoiceConfigFile) -> std::io::Result<()> {
    let path = voice_config_path()?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let data = serde_json::to_string_pretty(cfg)?;
    fs_atomic::atomic_write(&path, data.as_bytes(), None)?;
    Ok(())
}

pub(super) fn write_audit(event_type: &str, provider: &str, duration_ms: u64, success: bool) {
    let now = chrono::Utc::now().timestamp();
    let entry = VoiceAuditEntry {
        event_type: event_type.into(),
        timestamp: now,
        provider: provider.into(),
        duration_ms,
        success,
    };
    if let Ok(dir) = audit_dir() {
        let filename = format!("{}.jsonl", chrono::Utc::now().format("%Y-%m-%d"));
        let line = match serde_json::to_string(&entry) {
            Ok(s) => s,
            Err(_) => return,
        };
        use std::io::Write;
        if let Ok(mut f) = std::fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(dir.join(filename))
        {
            let _ = writeln!(f, "{}", line);
        }
    }
}

// ───────────────────────── T8.1: ASR ─────────────────────────

#[tauri::command]
pub async fn voice_transcribe(
    _state: State<'_, AppState>,
    audio_base64: String,
    mime: String,
) -> IpcResult<VoiceTranscribeResult> {
    let cfg = load_config();
    let provider = parse_provider(&cfg.asr_provider, VoiceProvider::Openai);
    let endpoint = cfg
        .asr_endpoint
        .unwrap_or_else(|| provider.default_asr_endpoint().to_owned());
    let api_key = cfg.asr_api_key.unwrap_or_default();
    if api_key.is_empty() {
        return Err(IpcError::Internal {
            message: "ASR API key not configured. Open Settings › Voice to set it.".into(),
        });
    }

    let start = std::time::Instant::now();
    let audio_bytes = base64::engine::general_purpose::STANDARD
        .decode(audio_base64)
        .map_err(|e| IpcError::Internal {
            message: format!("base64 decode: {e}"),
        })?;

    let client = reqwest::Client::new();
    let file_name = if mime.contains("wav") {
        "audio.wav"
    } else if mime.contains("mp3") || mime.contains("mpeg") {
        "audio.mp3"
    } else {
        "audio.webm"
    };

    let part = reqwest::multipart::Part::bytes(audio_bytes)
        .file_name(file_name)
        .mime_str(&mime)
        .map_err(|e| IpcError::Internal {
            message: format!("mime: {e}"),
        })?;

    let model = provider.asr_model().to_owned();

    let form = match provider {
        VoiceProvider::Zhipu => reqwest::multipart::Form::new()
            .part("file", part)
            .text("model", model),
        _ => reqwest::multipart::Form::new()
            .part("file", part)
            .text("model", model)
            .text("response_format", "verbose_json"),
    };

    let resp = client
        .post(&endpoint)
        .header("Authorization", format!("Bearer {api_key}"))
        .multipart(form)
        .send()
        .await
        .map_err(|e| IpcError::Internal {
            message: format!("ASR request failed: {e}"),
        })?;

    let status = resp.status();
    let body = resp.text().await.map_err(|e| IpcError::Internal {
        message: format!("ASR read body: {e}"),
    })?;

    let duration = start.elapsed().as_millis() as u64;

    if !status.is_success() {
        write_audit("voice.transcribe", provider.as_str(), duration, false);
        return Err(IpcError::Internal {
            message: format!("ASR API error {}: {}", status, &body[..body.len().min(500)]),
        });
    }

    let text = match provider {
        VoiceProvider::Zhipu => {
            #[derive(Deserialize)]
            struct ZhipuAsrResponse {
                text: Option<String>,
                choices: Option<Vec<ZhipuChoice>>,
            }
            #[derive(Deserialize)]
            struct ZhipuChoice {
                message: ZhipuMessage,
            }
            #[derive(Deserialize)]
            struct ZhipuMessage {
                content: String,
            }
            let parsed: ZhipuAsrResponse =
                serde_json::from_str(&body).map_err(|e| IpcError::Internal {
                    message: format!("ASR parse (zhipu): {e}"),
                })?;
            if let Some(t) = parsed.text {
                t
            } else {
                parsed
                    .choices
                    .unwrap_or_default()
                    .into_iter()
                    .next()
                    .map(|c| c.message.content)
                    .unwrap_or_default()
            }
        }
        _ => {
            #[derive(Deserialize)]
            struct WhisperResponse {
                text: String,
            }
            let parsed: WhisperResponse =
                serde_json::from_str(&body).map_err(|e| IpcError::Internal {
                    message: format!("ASR parse: {e}"),
                })?;
            parsed.text
        }
    };

    write_audit("voice.transcribe", provider.as_str(), duration, true);

    Ok(VoiceTranscribeResult {
        text,
        language: None,
        duration_ms: Some(duration),
    })
}


// ───────────────────────── Config CRUD ─────────────────────────

#[tauri::command]
pub async fn voice_get_config() -> IpcResult<VoiceConfig> {
    let cfg = load_config();
    let asr_p = parse_provider(&cfg.asr_provider, VoiceProvider::Openai);
    let tts_p = parse_provider(&cfg.tts_provider, VoiceProvider::Openai);
    let tts_voice = if tts_p.tts_voices().contains(&cfg.tts_voice.as_str()) {
        cfg.tts_voice.clone()
    } else {
        tts_p.default_voice().to_owned()
    };
    let tts_speed = if cfg.tts_speed <= 0.0 || cfg.tts_speed > 4.0 {
        1.0
    } else {
        cfg.tts_speed
    };
    Ok(VoiceConfig {
        asr_provider: asr_p.as_str().to_owned(),
        tts_provider: tts_p.as_str().to_owned(),
        asr_endpoint: cfg.asr_endpoint,
        asr_api_key_set: !cfg.asr_api_key.unwrap_or_default().is_empty(),
        tts_endpoint: cfg.tts_endpoint,
        tts_api_key_set: !cfg.tts_api_key.unwrap_or_default().is_empty(),
        tts_voice,
        tts_speed,
        hotkey: cfg.hotkey,
        available_asr_providers: VoiceProvider::all()
            .iter()
            .filter(|p| p.has_asr())
            .map(|p| p.as_str().to_owned())
            .collect(),
        available_tts_providers: VoiceProvider::all()
            .iter()
            .filter(|p| p.has_tts())
            .map(|p| p.as_str().to_owned())
            .collect(),
        asr_voices: Vec::new(),
        tts_voices: tts_p.tts_voices().iter().map(|s| s.to_string()).collect(),
    })
}

#[tauri::command]
pub async fn voice_set_config(args: VoiceConfigUpdate) -> IpcResult<()> {
    let mut cfg = load_config();
    if let Some(v) = args.asr_provider {
        let p = parse_provider(&Some(v), VoiceProvider::Openai);
        cfg.asr_provider = Some(p.as_str().to_owned());
        if cfg.asr_endpoint.is_none() {
            cfg.asr_endpoint = None;
        }
    }
    if let Some(v) = args.asr_endpoint {
        cfg.asr_endpoint = if v.is_empty() { None } else { Some(v) };
    }
    if let Some(v) = args.asr_api_key {
        cfg.asr_api_key = if v.is_empty() { None } else { Some(v) };
    }
    if let Some(v) = args.tts_provider {
        let p = parse_provider(&Some(v), VoiceProvider::Openai);
        cfg.tts_provider = Some(p.as_str().to_owned());
        if cfg.tts_endpoint.is_none() {
            cfg.tts_endpoint = None;
        }
        let default_v = p.default_voice().to_owned();
        if !p.tts_voices().contains(&cfg.tts_voice.as_str()) {
            cfg.tts_voice = default_v;
        }
    }
    if let Some(v) = args.tts_endpoint {
        cfg.tts_endpoint = if v.is_empty() { None } else { Some(v) };
    }
    if let Some(v) = args.tts_api_key {
        cfg.tts_api_key = if v.is_empty() { None } else { Some(v) };
    }
    if let Some(v) = args.tts_voice {
        cfg.tts_voice = v;
    }
    if let Some(v) = args.tts_speed {
        cfg.tts_speed = v;
    }
    if let Some(v) = args.hotkey {
        cfg.hotkey = v;
    }
    save_config(&cfg).map_err(|e| IpcError::Internal {
        message: format!("save voice config: {e}"),
    })
}

// ───────────────────────── T8.5: Audit log ─────────────────────────

#[tauri::command]
pub async fn voice_audit_log(
    _state: State<'_, AppState>,
    limit: Option<u32>,
) -> IpcResult<Vec<VoiceAuditEntry>> {
    let lim = limit.unwrap_or(50).min(200) as usize;
    let dir = match audit_dir() {
        Ok(d) => d,
        Err(_) => return Ok(Vec::new()),
    };

    let mut entries = Vec::new();
    let mut files: Vec<_> = std::fs::read_dir(&dir)
        .ok()
        .map(|rd| {
            rd.filter_map(|e| e.ok())
                .filter(|e| {
                    e.path()
                        .extension()
                        .map(|ext| ext == "jsonl")
                        .unwrap_or(false)
                })
                .collect()
        })
        .unwrap_or_default();

    files.sort_by_key(|b| std::cmp::Reverse(b.file_name()));

    for file in files {
        if entries.len() >= lim {
            break;
        }
        if let Ok(content) = std::fs::read_to_string(file.path()) {
            for line in content.lines().rev() {
                if entries.len() >= lim {
                    break;
                }
                if let Ok(entry) = serde_json::from_str::<VoiceAuditEntry>(line) {
                    entries.push(entry);
                }
            }
        }
    }

    entries.sort_by_key(|b| std::cmp::Reverse(b.timestamp));
    entries.truncate(lim);
    Ok(entries)
}
