carriers:
  ups:
    enabled: true
    upload_prefix: "UPS-GROUND"
    schedules:
      - name: 月度分区更新
        cron: "0 0 2 1 * *"
    source:
      carrier: UPS
      service: GROUND
      totalZip3: 902
    upload:
      maxRetries: 3
      retryDelay: 2
      requestInterval: 1
  usps:
    enabled: true
    upload_prefix: "USPS-GROUND"
    schedules:
      - name: 月度分区更新
        cron: "0 0 3 1 * *"
    source:
      carrier: USPS
      service: GROUND
      totalZip3: 930
    upload:
      maxRetries: 3
      retryDelay: 2
      requestInterval: 0.3
  fedex:
    enabled: true
    upload_prefix: "FedEx Ground"
    schedules:
      - name: 月度分区更新
        cron: "0 0 4 1 * *"
    source:
      carrier: FedEx
      service: Ground
      download_method: cdp
      cdp_port: 9222
      totalZip3: 1000
    upload:
      maxRetries: 3
      retryDelay: 2
      requestInterval: 1
