#!/usr/bin/env bash
# new-customer.sh — 一键生成白标客户交付包。
#
# Usage:
#   bash scripts/new-customer.sh <slug> \
#       --app-name "<品牌名>" \
#       --machine-id <uuid> \
#       --expires <1y|6mo|30d|YYYY-MM-DD>
#       [--packs <id1,id2>] \
#       [--hide <route1,route2>] \
#       [--primary-color <#HEX>] \
#       [--license-features <feat1,feat2>] \
#       [--output <dir>] \
#       [--dry-run] \
#       [--no-license]
#
# 典型示例（签跨境电商顾问白标给 acme 公司）：
#   bash scripts/new-customer.sh acme \
#       --app-name "Acme 跨境电商助手" \
#       --machine-id 1f4d1e2c-9b8a-4d2c-bc01-7e8a09f1b6c4 \
#       --expires 1y \
#       --packs cross_border_ecom \
#       --hide terminal,mcp,compare,logs \
#       --license-features cross_border_ecom
#
# 产物（默认 ./customers/<slug>/）：
#   customer.yaml   —— 白标配置（品牌 + preinstall + hidden_routes），复制到
#                      客户机器 ~/.hermes/customer.yaml 即生效
#   license.txt     —— 机器绑定的 ed25519 license token（--no-license 可跳过）
#   INSTALL.md      —— 给客户的安装手册（中文）
#   README.md       —— 给自己的记录（slug / 到期 / machine-id 摘要）

set -euo pipefail

usage() {
  sed -n '1,32p' "$0" | sed 's/^# \{0,1\}//'
  exit 1
}

# ---- parse args -----------------------------------------------------------

SLUG=""
APP_NAME=""
MACHINE_ID=""
EXPIRES=""
PACKS=""
HIDE=""
PRIMARY_COLOR=""
LICENSE_FEATURES=""
OUTPUT_DIR=""
DRY_RUN=0
NO_LICENSE=0

if [[ $# -lt 1 ]]; then usage; fi
case "$1" in
  -h|--help) usage ;;
esac
SLUG="$1"
shift

while [[ $# -gt 0 ]]; do
  case "$1" in
    --app-name)          APP_NAME="$2"; shift 2 ;;
    --machine-id)        MACHINE_ID="$2"; shift 2 ;;
    --expires)           EXPIRES="$2"; shift 2 ;;
    --packs)             PACKS="$2"; shift 2 ;;
    --hide)              HIDE="$2"; shift 2 ;;
    --primary-color)     PRIMARY_COLOR="$2"; shift 2 ;;
    --license-features)  LICENSE_FEATURES="$2"; shift 2 ;;
    --output)            OUTPUT_DIR="$2"; shift 2 ;;
    --dry-run)           DRY_RUN=1; shift ;;
    --no-license)        NO_LICENSE=1; shift ;;
    -h|--help)           usage ;;
    *) echo "unknown flag: $1" >&2; exit 2 ;;
  esac
done

# Slug 校验：只能 a-z0-9-_，因为要做目录名 + yaml id。
if ! [[ "$SLUG" =~ ^[a-z0-9][a-z0-9_-]*$ ]]; then
  echo "error: slug must match ^[a-z0-9][a-z0-9_-]*$ (got: '$SLUG')" >&2
  exit 2
fi

if [[ $NO_LICENSE -eq 0 ]]; then
  [[ -z "$MACHINE_ID" ]] && { echo "error: --machine-id required (or pass --no-license)" >&2; exit 2; }
  [[ -z "$EXPIRES"    ]] && { echo "error: --expires required (or pass --no-license)" >&2; exit 2; }
fi

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT_DIR="${OUTPUT_DIR:-$REPO_ROOT/customers/$SLUG}"

# ---- render customer.yaml -------------------------------------------------

# 拆 --packs / --hide 成 yaml 列表。空字符串 → 空数组 `[]`，让 yaml 永远
# parse-able 且不依赖 serde `#[serde(default)]`。
yaml_list_from_csv() {
  local csv="$1"
  if [[ -z "$csv" ]]; then echo "[]"; return; fi
  local out=""
  local IFS=','
  local item
  for item in $csv; do
    # trim + 给字符串加引号，Pack id / 路由名理论上都是 [a-z0-9_-]
    # 但给 hidden_routes 留冗余，防客户未来塞空格或中文。
    item="${item#"${item%%[![:space:]]*}"}"
    item="${item%"${item##*[![:space:]]}"}"
    out+="\"$item\","
  done
  echo "[${out%,}]"
}

PACKS_YAML="$(yaml_list_from_csv "$PACKS")"
HIDE_YAML="$(yaml_list_from_csv "$HIDE")"

render_customer_yaml() {
  cat <<EOF
# customer.yaml — generated by scripts/new-customer.sh for slug="$SLUG"
# Place this file at ~/.hermes/customer.yaml on the customer machine.
# See src-tauri/src/customer/mod.rs for the full schema.

schema_version: 1

brand:
  app_name: "${APP_NAME:-Corey}"
EOF
  if [[ -n "$PRIMARY_COLOR" ]]; then
    echo "  primary_color: \"$PRIMARY_COLOR\""
  fi
  cat <<EOF

navigation:
  # 这些入口会从侧边栏摘掉（URL 直达在 v0.2.1 后续加 URL 级拦截）。
  hidden_routes: $HIDE_YAML

packs:
  # 首次启动自动启用的 Pack id。
  preinstall: $PACKS_YAML
  # 要钉到主 section 的 Pack view id（可按需扩展）。
  pin_to_primary: []
  # 每个 Pack 的首启默认配置（可按需扩展）。
  config: {}
EOF
}

# ---- render INSTALL.md ----------------------------------------------------

render_install_md() {
  local license_section
  if [[ $NO_LICENSE -eq 1 ]]; then
    license_section="> 本包未附 license（--no-license）。功能受 license_feature 门禁的 Pack 会保持禁用。"
  else
    license_section="$(cat <<'SECTION'
## 4. 激活授权

1. 打开应用后，右上角头像 → 设置 → 许可证
2. 粘贴 `license.txt` 的完整内容到激活框
3. 点"激活"。状态变绿即生效。

> 许可证已绑定你本机（machine-id）。换机器需要重新签发。
SECTION
)"
  fi

  cat <<EOF
# ${APP_NAME:-Corey} 安装手册

> slug: \`$SLUG\` · 签发日期：$(date +%Y-%m-%d)

## 1. 下载与解压

把本压缩包下载到任意工作目录，解压得到：

\`\`\`
$SLUG/
├── customer.yaml   ← 白标配置
├── license.txt     ← 授权码（机器绑定）
├── INSTALL.md      ← 本文件
└── README.md       ← 快速摘要
\`\`\`

## 2. 安装应用

从官网下载 ${APP_NAME:-Corey} 安装包：

- macOS：双击 \`.dmg\`，拖入 Applications
- Windows：运行 \`.msi\`，按默认选项走完即可

首次启动后**不要急着操作**，先退出应用。

## 3. 放置白标配置

把 \`customer.yaml\` 复制到用户目录下的 \`.hermes/\`：

- macOS / Linux：\`~/.hermes/customer.yaml\`
- Windows：\`%USERPROFILE%\\.hermes\\customer.yaml\`

> 若 \`.hermes\` 目录不存在，先启动一次应用让它自动创建，再退出来放文件。

放好后重新启动应用：品牌名 / 侧边栏 / 预装 Pack 自动生效。

$license_section

## 5. 常见问题

- **启用 Pack 后提示 "license_feature required"**：说明 license.txt 的 features 里缺对应标识。联系我们重签。
- **品牌名没变**：确认 \`customer.yaml\` 放在 \`.hermes/\` 下（不是当前工作目录），且 \`schema_version: 1\`。
- **侧边栏仍有 \`--hide\` 列出的入口**：当前版本只拦截侧边栏，URL 直达暂不拦截；如需完全屏蔽请联系我们。

有问题直接回头找我们，别自己乱改 yaml — 乱改反而会触发 "invalid; ignoring" 回退到默认。
EOF
}

# ---- render README.md（给自己看的） --------------------------------------

render_readme_md() {
  cat <<EOF
# Customer Bundle · $SLUG

| 字段 | 值 |
|---|---|
| slug | \`$SLUG\` |
| app_name | ${APP_NAME:-Corey} |
| packs.preinstall | $PACKS |
| hidden_routes | $HIDE |
| primary_color | ${PRIMARY_COLOR:-（默认金色）} |
| machine-id | ${MACHINE_ID:-（未绑定）} |
| expires | ${EXPIRES:-（未设置）} |
| license features | ${LICENSE_FEATURES:-（无）} |
| 签发日期 | $(date +%Y-%m-%d) |
| 签发脚本 | \`scripts/new-customer.sh\` |

## 复签须知

如果客户换机：

\`\`\`bash
bash scripts/mint-license.sh <user-id> \\
    --machine-id <new-uuid> \\
    --expires ${EXPIRES:-1y} \\
    ${LICENSE_FEATURES:+--features "$LICENSE_FEATURES"}
\`\`\`

只重发 \`license.txt\` 即可，\`customer.yaml\` 保持不变。
EOF
}

# ---- do it ----------------------------------------------------------------

if [[ $DRY_RUN -eq 1 ]]; then
  echo "# === dry-run: would write to $OUTPUT_DIR ==="
  echo "# --- customer.yaml ---"
  render_customer_yaml
  echo
  echo "# --- INSTALL.md (first 40 lines) ---"
  render_install_md | head -40
  echo
  echo "# --- README.md ---"
  render_readme_md
  exit 0
fi

mkdir -p "$OUTPUT_DIR"
render_customer_yaml > "$OUTPUT_DIR/customer.yaml"
render_install_md    > "$OUTPUT_DIR/INSTALL.md"
render_readme_md     > "$OUTPUT_DIR/README.md"

# License —— 委托给 mint-license.sh。
if [[ $NO_LICENSE -eq 0 ]]; then
  LICENSE_ARGS=(--machine-id "$MACHINE_ID" --expires "$EXPIRES")
  [[ -n "$LICENSE_FEATURES" ]] && LICENSE_ARGS+=(--features "$LICENSE_FEATURES")

  # mint-license.sh 的第一个位置参是 user-id。我们用 "$SLUG@customer" 做稳定
  # 标识；客户侧不会看到这个字段（它只在 license token 内部，用于审计）。
  if bash "$REPO_ROOT/scripts/mint-license.sh" "$SLUG@customer" "${LICENSE_ARGS[@]}" > "$OUTPUT_DIR/license.txt" 2>/tmp/new-customer-mint.err; then
    :
  else
    echo "error: mint-license.sh failed. See /tmp/new-customer-mint.err" >&2
    cat /tmp/new-customer-mint.err >&2 || true
    exit 3
  fi
fi

# ---- 摘要 -----------------------------------------------------------------

{
  echo
  echo "──────────────────────── Customer bundle ready ────────────────────────"
  echo "  slug      : $SLUG"
  echo "  output    : $OUTPUT_DIR"
  echo "  app_name  : ${APP_NAME:-Corey}"
  echo "  packs     : ${PACKS:-（无）}"
  echo "  hidden    : ${HIDE:-（无）}"
  if [[ $NO_LICENSE -eq 0 ]]; then
    echo "  expires   : $EXPIRES"
    echo "  machine   : $MACHINE_ID"
  else
    echo "  license   : skipped (--no-license)"
  fi
  echo "  files     :"
  for f in customer.yaml INSTALL.md README.md license.txt; do
    if [[ -f "$OUTPUT_DIR/$f" ]]; then
      echo "              - $f ($(wc -c < "$OUTPUT_DIR/$f" | tr -d ' ') bytes)"
    fi
  done
  echo "───────────────────────────────────────────────────────────────────────"
  echo
  echo "下一步：把 $OUTPUT_DIR 打成 zip 发给客户，按 INSTALL.md 走。"
} >&2
